trigger:
  branches:
    include:
      - main  # Change to the branch you want to trigger the deployment on, e.g., 'master'

pool:
  name: 'Default'  # Use the default hosted agent pool or your self-hosted agent pool if needed

jobs:
- job: DeployPHPWebsite
  displayName: 'Deploy PHP website to Nginx server'
  steps:

    # 1. Install dependencies (e.g., PHP 8.1 and PHP-FPM)
    - task: AzureCLI@2
      displayName: 'Install PHP 8.1 and PHP-FPM'
      inputs:
        azureSubscription: 'Your Azure Subscription'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Update the package list and install PHP 8.1 and PHP-FPM
          sudo add-apt-repository ppa:ondrej/php
          sudo apt-get update
          sudo apt-get install -y php8.1 php8.1-fpm php8.1-mysql php8.1-xml php8.1-mbstring

    # 2. Deploy PHP files to the Nginx server
    - task: SSH@0
      displayName: 'Deploy Website Files to Nginx'
      inputs:
        sshEndpoint: 'NginxServerConnection'  # Configure this SSH endpoint in Azure DevOps
        runOptions: 'inline'
        inline: |
          # Navigate to the correct directory and deploy the files
          cd /var/www/your_php_site
          rm -rf *  # Optional: Remove old files
          # Deploy new files from GitHub repository
          git clone https://github.com/yourusername/yourrepository.git .
          sudo chown -R www-data:www-data /var/www/your_php_site
          sudo chmod -R 755 /var/www/your_php_site

    # 3. Restart Nginx to apply new files
    - task: SSH@0
      displayName: 'Restart Nginx'
      inputs:
        sshEndpoint: 'NginxServerConnection'  # Configure this SSH endpoint in Azure DevOps
        runOptions: 'inline'
        inline: |
          # Restart Nginx to apply the new files
          sudo systemctl restart nginx
          sudo systemctl restart php8.1-fpm

    # Optional: You can add more tasks, like running tests or checking logs.
