trigger:
- main

pool:
  name: 'windows' # Replace with the name of your self-hosted agent pool

variables:
  DEPLOYMENT_DIR: '/var/www/html/Car_and_Bike_Rental_Website'
  NGINX_SERVER: 'ubu'

steps:

- script: |
    echo "Syncing files to Nginx server..."
    rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" . $(ubu):$(/var/www/html/Car_and_Bike_Rental_Website)
  displayName: 'Sync Files with rsync'

- script: |
    echo "Setting permissions and restarting Nginx..."
    ssh -o StrictHostKeyChecking=no $(ubu) "chmod -R 755 $(/var/www/html/Car_and_Bike_Rental_Website)"
    ssh -o StrictHostKeyChecking=no $(ubu) "sudo systemctl restart nginx"
  displayName: 'Set Permissions and Restart Nginx'
