trigger:
  branches:
    include:
      - main  # Change to the branch you want to trigger the deployment on, e.g., 'master'

pool:
  name: 'windows'  # Use the default hosted agent pool or your self-hosted agent pool if needed

jobs:
- job: DeployPHPWebsite
  displayName: 'Deploy PHP website to Nginx server'
  steps:


    # 2. Deploy PHP files to the Nginx server
    - task: SSH@0
      displayName: 'Deploy Website Files to Nginx'
      inputs:
        sshEndpoint: 'NginxServerConnection'  # Configure this SSH endpoint in Azure DevOps
        runOptions: 'inline'
        inline: |
          
          cd /var/www/Car_and_Bike_Rental_Website
          rm -rf *  # Optional: Remove old files
          
          git clone  .https://github.com/bhartilalit683/Car_and_Bike_Rental_Website.git
          sudo chown -R www-data:www-data /var/www/your_php_site
          sudo chmod -R 755 /var/www/your_php_site

    # 3. Restart Nginx to apply new files
    - task: SSH@0
      displayName: 'Restart Nginx'
      inputs:
        sshEndpoint: 'ubuntu'  # Configure this SSH endpoint in Azure DevOps
        runOptions: 'inline'
        inline: |
          # Restart Nginx to apply the new files
          sudo systemctl restart nginx
          sudo systemctl restart php8.1-fpm

    # Optional: You can add more tasks, like running tests or checking logs.
